### ISSUE TITLE
Array Type

### ISSUE THREAD

**Issue by ZombieRoxtar** [ZombieRoxtar/Hotkey-Blocker#1]
I declared a managed array of keys to make future changes to the keys faster. Subsequently, I had to calculate and store the array length. What's the best choice here?
This issue is summarized in the comment on line 21.

**Comment by aroxby** [comment]
Yes, when you use a C array you have to know the size.  Since the size is known at compile time this can be a `const static int`.  If you want you and use a `std::list<int>` that will manage the memory for you, but you really only need that if you want to add/remove elements at run time.

**Comment by ZombieRoxtar** [comment]
I wanted to not have to put a # in the [] so array modding is fast and easy. Can I `const static` the int that holds a calculated array length?

**Comment by ZombieRoxtar** [comment]
I can and did. Is that the best thing?

**Comment by aroxby** [comment]
Hey, try this one `const static size = sizeof(arr)/sizeof(arr[0]);` :-D

**Comment by ZombieRoxtar** [comment]
Is it not cool to have the size int update itself at compile time?

**Comment by aroxby** [comment]
That is fine.  See my revised comment.

**Comment by ZombieRoxtar** [comment]
You forgot the data type: `const static int arraySize = sizeof(cappedKeys) / sizeof(cappedKeys[0]);`

**Comment by aroxby** [comment]
Thanks!
Make that a `size_t` (or maybe `auto`)
