### ISSUE TITLE
PostMessage vs. Send Message

### ISSUE THREAD

**Issue by ZombieRoxtar** [ZombieRoxtar/Hotkey-Blocker#3]
I really couldn't care about PostMessage vs Send Message, but I want to be sure both messages are received and in that order.
This issue is summarized in the comment block on lines 64-67.

**Comment by aroxby** [comment]
PostMessage places the message on the queue, since your app is single threaded I believe you have the this guarantee.

**Comment by ZombieRoxtar** [comment]
But foreground games are mutli-threaded. Also, if can you mod the .cpp based on your recommendation(s)? The issues with comments listed need these comments removed after code review.

**Comment by aroxby** [comment]
There is only one input queue for starcraft, don't worry about how many threads may be reading it, that's not your problem.
I'll get around to the cpp eventually.
