### ISSUE TITLE
App Lag

### ISSUE THREAD

**Issue by ZombieRoxtar** [ZombieRoxtar/Hotkey-Blocker#6]
If you run this program and focus Notepad2 and then press F1, then Notepad2 will lock up until you focus the console window again.

**Comment by aroxby** [comment]
Your app is _busy waiting_ and eating an entire CPU core. Add `Sleep(0)` somewhere in the main loop, or even better `Sleep(10)`.

More detail:
The kernel gives each running a process a _time slice_, processes which are still executing at the end of their time slice are _preempted_, or interrupted, by the kernel. The kernel believes you are doing something useful for the duration of that time slice.  You can tell the kernel that you're not doing anything of particular interest with `Sleep(0)`.  `Sleep()` tells the kernel that your thread is done and it should switch to another thread.  You can optionally specify a minimum delay (`Sleep(10)`) which tells the kernel "I'm done and won't be ready again for at least 10ms, feel free to do other things during that time".

**Comment by aroxby** [comment]
Sorry I haven't made any code contributions myself, we're really busy at work but maybe tonight I'll post something.

**Comment by ZombieRoxtar** [comment]
The sleep worked pretty good. Now the active window gets spammed with key presses until you close the program.

**Comment by aroxby** [comment]
That's due to the repeat message bug I mentioned earlier ;-)

**Comment by ZombieRoxtar** [comment]
Yeah after I GetForegroundWindow() what do I test to see if it's one of mine?

**Comment by aroxby** [comment]
1) How could it be?  you don't have an actual window which can obtain focus.
2) Why does it matter?  You listen for hotkey events not keystroke events.
3) The MSG (and thus WndProc) contains a destination window (which should always be yours), so try `GetForegroundWindow()==hWnd` to test if your window is the foreground window.

**Comment by ZombieRoxtar** [comment]
Well the program lagged when the console was active but that was the same bug and the loop is fixed now.

**Comment by aroxby** [comment]
I should point out, there is GetConsoleWindow() which will retrieve the hWnd of the console window.
